# Generated by Django 6.0.2 on 2026-02-20 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_image_product_mage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='mage',
            new_name='image',
        ),
    ]
