# Generated by Django 6.0.2 on 2026-02-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('pendente', 'Pendente de Entrega'), ('entregue', 'Entregue'), ('cancelada', 'Cancelada')], default='pendente', max_length=20),
        ),
    ]
