# Generated by Django 6.0.2 on 2026-03-01 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_order_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promotion_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Percentagem de desconto entre 0 e 50%', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='product',
            name='promotion_price',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
    ]
