# Generated by Django 6.0.2 on 2026-03-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_promotion_percentage_product_promotion_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='multibanco', max_length=20),
        ),
    ]
