# Generated by Django 6.0.2 on 2026-03-02 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_order_managed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStats',
            fields=[
            ],
            options={
                'verbose_name': 'Estatística de Venda',
                'verbose_name_plural': 'Estatísticas de Vendas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.order',),
        ),
        migrations.AlterField(
            model_name='order',
            name='managed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
